"""create_orders_table

Revision ID: a2a17bc7f25b
Revises: a30ddfed48fa
Create Date: 2025-05-29 11:55:45.015946

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "a2a17bc7f25b"
down_revision: Union[str, None] = "a30ddfed48fa"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    sa.Enum("pending", "accepted", "executed", "canceled", name="orderstatus").create(op.get_bind())
    op.create_table(
        "orders",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("author_id", sa.String(length=20), nullable=False),
        sa.Column("address", sa.String(length=255), nullable=False),
        sa.Column("time", sa.DateTime(), nullable=False),
        sa.Column(
            "status",
            postgresql.ENUM("pending", "accepted", "executed", "canceled", name="orderstatus", create_type=False),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["author_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("orders")
    sa.Enum("pending", "accepted", "executed", "canceled", name="orderstatus").drop(op.get_bind())
    # ### end Alembic commands ###
