"""edit_orderstatus_enum

Revision ID: a3f9ee542135
Revises: a2a17bc7f25b
Create Date: 2025-05-29 16:48:45.951061

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from alembic_postgresql_enum import TableReference

# revision identifiers, used by Alembic.
revision: str = "a3f9ee542135"
down_revision: Union[str, None] = "a2a17bc7f25b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.sync_enum_values(
        enum_schema="public",
        enum_name="orderstatus",
        new_values=["pending", "accepted", "completed", "rejected", "canceled"],
        affected_columns=[TableReference(table_schema="public", table_name="orders", column_name="status")],
        enum_values_to_rename=[],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.sync_enum_values(
        enum_schema="public",
        enum_name="orderstatus",
        new_values=["pending", "accepted", "executed", "canceled"],
        affected_columns=[TableReference(table_schema="public", table_name="orders", column_name="status")],
        enum_values_to_rename=[],
    )
    # ### end Alembic commands ###
